apiVersion: v1
kind: Service
metadata:
  name: location-grpc
  labels:
    app: location-grpc
spec:
  selector:
    app: location-grpc
  type: NodePort
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-grpc
  name: location-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-grpc
  template:
    metadata:
      labels:
        service: location-grpc
    spec:
      containers:
        - image: heppiedoc/udaconnect-location-producer:latest
          name: location-grpc
          imagePullPolicy: Always
          env:
            - name: TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: TOPIC_NAME
            - name: KAFKA_HOST_PRODUCER
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_HOST_PRODUCER
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_PORT
      restartPolicy: Always
